#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use Almhdy\Simy\Core\CommandHandler;
use Almhdy\Simy\Core\Command\ServeCommand;
use Almhdy\Simy\Core\Command\MakeControllerCommand;
use Almhdy\Simy\Core\Command\CreateMigrationCommand;
use Almhdy\Simy\Core\Command\RunMigrationsCommand;
use Almhdy\Simy\Core\Command\DeleteMigrationCommand;

// Load environment variables from .env file
$dotenv = Dotenv::createImmutable(__DIR__.'/app');
$dotenv->load();

$commandHandler = new CommandHandler();

// Register commands
$commandHandler->registerCommand('make:controller', new MakeControllerCommand());
$commandHandler->registerCommand('serve', new ServeCommand());
$commandHandler->registerCommand('create:migration', new CreateMigrationCommand());
$commandHandler->registerCommand('migrate', new RunMigrationsCommand());
$commandHandler->registerCommand('migrate:delete', new DeleteMigrationCommand());

// Run the command handler
$commandHandler->run($argv);